// Amplify Auth config
import { Amplify } from "aws-amplify";
import config from "../amplifyconfiguration.json";
// End Amplify Auth config

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../components/AuthProvider";

Amplify.configure(config);

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "YellowBall",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider />
        {children}
      </body>
    </html>
  );
}
